# Generated by Django 4.1.7 on 2023-07-30 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
