# Generated by Django 4.1.7 on 2023-07-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=120, unique='True'),
        ),
    ]
