# Generated by Django 4.1.7 on 2023-08-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='has_uploaded_paper',
            field=models.BooleanField(default=False),
        ),
    ]
