# Generated by Django 4.1.7 on 2023-08-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_conference_conference_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='conference_user',
            field=models.CharField(default='Not present', max_length=150),
        ),
    ]
