# Generated by Django 4.1.7 on 2023-08-19 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=70)),
                ('highest_qualification', models.CharField(max_length=150)),
                ('experience', models.CharField(max_length=150)),
                ('designations', models.CharField(max_length=70)),
                ('organization', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=15)),
                ('whats_app_number', models.CharField(max_length=15)),
                ('password_reviewer', models.CharField(max_length=70)),
                ('date_reviewer', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo_upload', models.FileField(upload_to='reviewer/profile-photos/')),
                ('resume_upload', models.FileField(upload_to='reviewer/profile-resume/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='reviewerdata_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='reviewerdata_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
