# Generated by Django 4.1.7 on 2023-08-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer_data',
            old_name='email',
            new_name='reviewer_email',
        ),
        migrations.RenameField(
            model_name='reviewer_data',
            old_name='name',
            new_name='reviewer_name',
        ),
        migrations.RenameField(
            model_name='reviewer_data',
            old_name='number',
            new_name='reviewer_number',
        ),
    ]
