# Generated by Django 4.1.7 on 2023-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_rename_email_reviewer_data_reviewer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer_data',
            name='password_reviewer',
        ),
        migrations.AlterField(
            model_name='reviewer_data',
            name='password',
            field=models.CharField(max_length=70),
        ),
    ]
