# Generated by Django 4.1.7 on 2023-08-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_rename_reviewer_email_reviewer_data_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer_data',
            name='reviewer_id',
            field=models.IntegerField(default=0),
        ),
    ]
