# Generated by Django 4.1.7 on 2023-08-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_reviewer_data_reviewer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer_data',
            name='is_ok',
            field=models.BooleanField(default=False),
        ),
    ]
