# Generated by Django 4.1.7 on 2023-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_reviewer_data_is_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer_data',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
