# Generated by Django 4.1.7 on 2023-08-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0002_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_upload',
            field=models.FileField(upload_to='papers/',null=False),
        ),
    ]
