# Generated by Django 4.1.7 on 2023-08-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
