# Generated by Django 4.1.7 on 2023-08-08 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_conference'),
        ('singup', '0011_paper_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='login.conference'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
