# Generated by Django 4.1.7 on 2023-08-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0015_paper_has_uploaded_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='paper',
            name='Auth_affiliation',
            field=models.CharField(default='No affiliation', max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='Auth_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='paper',
            name='Auth_mobile',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='corresponding_auth_affiliation',
            field=models.CharField(default='No affiliation', max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='corresponding_auth_email',
            field=models.EmailField(default='corresponding@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='paper',
            name='corresponding_auth_mobile',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='corresponding_auth_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='other_auth_affiliation',
            field=models.CharField(default='No affiliation', max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='other_auth_email',
            field=models.EmailField(default='other@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='paper',
            name='other_auth_mobile',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='other_auth_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_keyword',
            field=models.CharField(default='No keywords', max_length=100),
        ),
    ]
