# Generated by Django 4.1.7 on 2023-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0016_remove_paper_expiry_date_paper_auth_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='other_auth_email',
            field=models.CharField(default='other@example.com', max_length=150),
        ),
    ]
