# Generated by Django 4.1.7 on 2023-08-15 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_conference_has_uploaded_paper'),
        ('singup', '0018_paper_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='resubmit_papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField()),
                ('title_paper', models.CharField(max_length=70)),
                ('Auth_name', models.CharField(max_length=70)),
                ('paper_description', models.CharField(max_length=500)),
                ('paper_upload', models.FileField(upload_to='papers/')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('has_uploaded_paper', models.BooleanField(default=False)),
                ('Auth_email', models.EmailField(default='example@example.com', max_length=254)),
                ('Auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('Auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('corresponding_auth_name', models.CharField(default='Unknown', max_length=100)),
                ('corresponding_auth_email', models.EmailField(default='corresponding@example.com', max_length=254)),
                ('corresponding_auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('corresponding_auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('other_auth_name', models.CharField(default='Unknown', max_length=100)),
                ('other_auth_email', models.CharField(default='other@example.com', max_length=150)),
                ('other_auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('other_auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('paper_keyword', models.CharField(default='No keywords', max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('conference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='login.conference')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
