# Generated by Django 4.1.7 on 2023-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0020_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
