# Generated by Django 4.1.7 on 2023-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0021_customuser_is_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resubmit_papers',
            name='comment1',
            field=models.CharField(default='Not Available', max_length=500),
        ),
        migrations.AddField(
            model_name='resubmit_papers',
            name='comment2',
            field=models.CharField(default='Not Available', max_length=500),
        ),
        migrations.AddField(
            model_name='resubmit_papers',
            name='comment3',
            field=models.CharField(default='Not Available', max_length=500),
        ),
    ]
