# Generated by Django 4.1.7 on 2023-08-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0022_resubmit_papers_comment1_resubmit_papers_comment2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='comment1',
            field=models.CharField(default='Not Available', max_length=500),
        ),
        migrations.AddField(
            model_name='paper',
            name='comment2',
            field=models.CharField(default='Not Available', max_length=500),
        ),
        migrations.AddField(
            model_name='paper',
            name='comment3',
            field=models.CharField(default='Not Available', max_length=500),
        ),
    ]
