# Generated by Django 4.1.7 on 2023-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0023_paper_comment1_paper_comment2_paper_comment3'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='assigned_reviewers_id',
            field=models.IntegerField(default=0),
        ),
    ]
