# Generated by Django 4.1.7 on 2023-08-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0024_paper_assigned_reviewers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='assigned_reviewers_id',
            field=models.IntegerField(default=None),
        ),
    ]
