# Generated by Django 4.1.7 on 2023-08-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0025_alter_paper_assigned_reviewers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resubmit_papers',
            name='assigned_reviewers_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='assigned_reviewers_id',
            field=models.IntegerField(default=0),
        ),
    ]
