# Generated by Django 4.1.7 on 2023-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0026_resubmit_papers_assigned_reviewers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='comment1',
            field=models.CharField(default='Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='comment2',
            field=models.CharField(default='Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='comment3',
            field=models.CharField(default='Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resubmit_papers',
            name='comment1',
            field=models.CharField(default='Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resubmit_papers',
            name='comment2',
            field=models.CharField(default='Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resubmit_papers',
            name='comment3',
            field=models.CharField(default='Not Available', max_length=1000),
        ),
    ]
