# Generated by Django 4.1.7 on 2023-08-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_alter_reviewer_data_password'),
        ('singup', '0027_alter_paper_comment1_alter_paper_comment2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='assigned_reviewers_id',
        ),
        migrations.RemoveField(
            model_name='resubmit_papers',
            name='assigned_reviewers_id',
        ),
        migrations.AddField(
            model_name='paper',
            name='assigned_reviewers',
            field=models.ManyToManyField(related_name='assigned_papers', to='reviewer.reviewer_data'),
        ),
        migrations.AddField(
            model_name='resubmit_papers',
            name='assigned_reviewers',
            field=models.ManyToManyField(related_name='resubmit_papers', to='reviewer.reviewer_data'),
        ),
    ]
