# Generated by Django 4.1.7 on 2023-08-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0028_remove_paper_assigned_reviewers_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='reviewer_comments',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resubmit_papers',
            name='reviewer_comments',
            field=models.JSONField(default=dict),
        ),
    ]
