# Generated by Django 4.1.7 on 2023-08-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0030_rename_reviewer_comments_paper_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='comments',
        ),
        migrations.AddField(
            model_name='paper',
            name='reviewer_comments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
