# Generated by Django 4.1.7 on 2023-08-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0031_remove_paper_comments_paper_reviewer_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resubmit_papers',
            name='comments',
        ),
        migrations.AddField(
            model_name='resubmit_papers',
            name='reviewer_comments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
