# Generated by Django 4.1.7 on 2023-08-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0032_remove_resubmit_papers_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_conference_admin',
            field=models.BooleanField(default=False),
        ),
    ]
