# Generated by Django 4.1.7 on 2023-08-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0033_customuser_is_conference_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
